katharsis-project/katharsis-framework

pom.xml

- mvn validate goal will trigger the enforcer
- ensures the JDK used to compile is the version we claim to support

add maven-enforcer-plugin

---

katharsis-core/src/main/java/io/katharsis/dispatcher/controller/resource/ResourcePatch.java
katharsis-core/src/test/java/io/katharsis/dispatcher/controller/resource/ResourcePatchTest.java

Commit fixes the issue. Test slightly extended to cover the problematic case too.
Fixes #50

Core #50:  PATCH fails for fields that where null before

---

pom.xml

I fixed a maven configuration so that maven accepts all java versions above 1.7
Currently it only accepts 1.7 and **1.8**! Meaning if I use 1.8.0_101 it will fail.

allow all java versions > 1.7

---

katharsis-core/src/main/java/io/katharsis/resource/registry/responseRepository/RelationshipRepositoryAdapter.java
katharsis-core/src/main/java/io/katharsis/resource/registry/responseRepository/ResourceRepositoryAdapter.java
katharsis-core/src/main/java/io/katharsis/resource/registry/responseRepository/ResponseRepository.java
katharsis-jpa/src/main/java/io/katharsis/jpa/JpaModule.java
katharsis-jpa/src/main/java/io/katharsis/jpa/JpaRelationshipRepository.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/AbstractJpaQueryImpl.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/JoinRegistry.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/backend/JpaQueryBackend.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/backend/criteria/JpaCriteriaQueryBackend.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/backend/querydsl/QuerydslQueryBackend.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/backend/querydsl/QuerydslUtils.java
katharsis-jpa/src/test/java/io/katharsis/jpa/AbstractJpaJerseyTest.java
katharsis-jpa/src/test/java/io/katharsis/jpa/JpaQuerySpecEndToEndTest.java
katharsis-jpa/src/test/java/io/katharsis/jpa/repository/JpaRelationshipRepositoryTestBase.java

When you tried to query a to-many relation it didn't produce a proper result.
Reproduction of the issue is found in JpaRelationshipRepositoryTestBase class.
I had to disable the QueryDSL tests because the QueryFactory for QueryDsl still
cannot handle to-many type of queries properly.

Fix to-many relationships in JPAModule

---

katharsis-parent/pom.xml

From the maven docs for deploy:deploy:
Binds by default to the lifecycle phase: deploy.
Because of this binding the deploy target ran twice because it got
registered a second time. After removing the extra binding declaration
the deploy ran once for each module, just as it should.

remove deploy lifecycle binding from parent pom

---

katharsis-jpa/pom.xml

Instead of using a plugin, just use the build in annotation processing
support that maven-compiler-plugin has out of the box. It works by
default if you have an annotation processor on your compile classpath.

simpler annotation processing for querydsl

---

katharsis-core/src/main/java/io/katharsis/queryspec/DefaultQuerySpecDeserializer.java
katharsis-core/src/test/java/io/katharsis/queryspec/repository/DefaultQuerySpecDeserializerTest.java

For larger datasets it usually it is mandatory to provide pagination
parameters. Otherwise the server either breaks down or takes long to a
nswer. This is is not obvious when working as a user in the browser and
usually leads to exactly this problem. There should be the possiblity to
declare a default page size if none is set explictly.
new API:
DefaultQuerySpecDeserializer.setDefaultOffset(...)
DefaultQuerySpecDeserializer.setDefaultLimit(...)

#137 Support default pagination

---

katharsis-core/src/main/java/io/katharsis/resource/registry/ResourceRegistry.java
katharsis-core/src/test/java/io/katharsis/resource/registry/ResourceRegistryTest.java
katharsis-rs/src/main/java/io/katharsis/resource/registry/UriInfoServiceUrlProvider.java
katharsis-rs/src/main/java/io/katharsis/rs/KatharsisFeature.java
katharsis-rs/src/main/java/io/katharsis/rs/KatharsisFilter.java

fixed mixup of UriInfoServiceUrlProvider and ConstantServiceUrlProvider.
Switched to a thread-local solution for now since the actual URL is only
available at request-time.
With Katharsis 3.0 there is a potential to clean this up further by
mothing the url handling out of the serialization stack.

#140 UriInfoServiceUrlProvider not working

---

katharsis-client/pom.xml
katharsis-client/src/main/java/io/katharsis/client/KatharsisClient.java
katharsis-client/src/main/java/io/katharsis/client/http/HttpAdapter.java
katharsis-client/src/main/java/io/katharsis/client/http/okhttp/OkHttpAdapter.java
katharsis-client/src/main/java/io/katharsis/client/http/okhttp/OkHttpAdapterListener.java
katharsis-client/src/main/java/io/katharsis/client/http/okhttp/OkHttpAdapterListenerBase.java
katharsis-client/src/main/java/io/katharsis/client/internal/AbstractStub.java
katharsis-client/src/main/java/io/katharsis/client/internal/RelationshipRepositoryStubImpl.java
katharsis-client/src/main/java/io/katharsis/client/internal/ResourceRepositoryStubImpl.java
katharsis-client/src/main/java/io/katharsis/client/module/HttpAdapterAware.java
katharsis-client/src/test/java/io/katharsis/client/AbstractClientTest.java
katharsis-client/src/test/java/io/katharsis/client/ModuleTest.java
katharsis-core/src/main/java/io/katharsis/module/ModuleRegistry.java
katharsis-core/src/test/java/io/katharsis/module/ModuleTest.java
katharsis-jpa/src/test/java/io/katharsis/jpa/AbstractJpaJerseyTest.java
katharsis-validation/src/test/java/io/katharsis/validation/AbstractValidationTest.java

partial refactoring of http handling:
- HttpAdapter interface introduced to support implementations other than OkHttp in the future
- HttpAdapterAware interface implemented to let modules customize the http adapter
- OkHttpClient updated to current version
- OkHttpClient.Builder used to create OkHttpClient
- OkHttpAdapterListener to let modules modify okhttp during build process

#174 Make katharsis-client customizable with modules

---

katharsis-client/src/main/java/io/katharsis/client/KatharsisClient.java
katharsis-client/src/main/java/io/katharsis/client/QuerySpecResourceRepositoryStub.java
katharsis-client/src/main/java/io/katharsis/client/ResourceRepositoryStub.java
katharsis-client/src/main/java/io/katharsis/client/internal/ResourceRepositoryStubImpl.java
katharsis-client/src/test/java/io/katharsis/client/ExceptionTest.java
katharsis-client/src/test/java/io/katharsis/client/ModuleTest.java
katharsis-client/src/test/java/io/katharsis/client/QueryParamsClientTest.java
katharsis-client/src/test/java/io/katharsis/client/QuerySpecClientTest.java

introduced create(...) method next to save() method to perform an explicit push.
This breaks the current (wrong) contract of just having a save. A method setPushAlways(...) is provided on KatharisClient to enable the old behavior. For the next release it will be enabled to maintain backward
compatibility, but at some point it will be switched to the proper behavio.

#177 Properly support patch/post semantic in katharsis-client

---

katharsis-core/src/main/java/io/katharsis/errorhandling/ErrorResponse.java
katharsis-core/src/main/java/io/katharsis/errorhandling/exception/BadRequestException.java
katharsis-core/src/main/java/io/katharsis/errorhandling/exception/InternalServerErrorException.java
katharsis-core/src/main/java/io/katharsis/errorhandling/mapper/DefaultExceptionMapperLookup.java
katharsis-core/src/main/java/io/katharsis/errorhandling/mapper/KatharsisExceptionMapper.java
katharsis-core/src/main/java/io/katharsis/jackson/exception/JsonDeserializationException.java
katharsis-core/src/main/java/io/katharsis/jackson/exception/JsonSerializationException.java
katharsis-core/src/main/java/io/katharsis/jackson/exception/ParametersDeserializationException.java
katharsis-core/src/main/java/io/katharsis/repository/exception/RepositoryMethodException.java
katharsis-core/src/main/java/io/katharsis/resource/exception/RequestBodyNotFoundException.java
katharsis-core/src/main/java/io/katharsis/resource/exception/ResourceException.java
katharsis-core/src/main/java/io/katharsis/response/HttpStatus.java
katharsis-core/src/main/java/io/katharsis/security/ForbiddenException.java
katharsis-core/src/main/java/io/katharsis/security/UnauthorizedException.java
katharsis-core/src/test/java/io/katharsis/errorhandling/exception/KatharsisExceptionMapperTest.java

- add exception and mapper for UNAUTHORIZED_401
- add exception and mapper for FORBIDDEN_403
- add BadRequestException as supertype for all 400 exceptions
- add InternalSerververErrorException as supertype for all 500
- unmap everything on client-side

#182 Improve client-side exception mapping

---

katharsis-core/src/main/java/io/katharsis/module/InitialzingModule.java
katharsis-core/src/main/java/io/katharsis/module/ModuleRegistry.java
katharsis-core/src/test/java/io/katharsis/module/ModuleTest.java

currently modules just have a configure method where katharsis is not yet up and some things are not available. There should be an additional init() method that is invoked later once katharsis is up.
=> introduced new interface InitializingModule with that method

#186 Add init support to module lifecycle

---

katharsis-core/src/main/java/io/katharsis/queryspec/FilterOperator.java
katharsis-core/src/main/java/io/katharsis/queryspec/InMemoryEvaluator.java
katharsis-core/src/main/java/io/katharsis/utils/PropertyUtils.java
katharsis-core/src/test/java/io/katharsis/queryspec/InMemoryEvaluatorTest.java

- proper total count computation
- support to traverse multi-valued properties

#104 QuerySpec in-memory filtering fixes

---

katharsis-jpa/src/main/java/io/katharsis/jpa/JpaEntityRepository.java
katharsis-jpa/src/main/java/io/katharsis/jpa/JpaModule.java
katharsis-jpa/src/main/java/io/katharsis/jpa/JpaRelationshipRepository.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/JpaRequestContext.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/AbstractJpaQueryImpl.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/backend/querydsl/QuerydslExecutorImpl.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/backend/querydsl/QuerydslQueryBackend.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/backend/querydsl/QuerydslQueryImpl.java
katharsis-jpa/src/main/java/io/katharsis/jpa/query/JpaQuery.java
katharsis-jpa/src/main/java/io/katharsis/jpa/query/querydsl/QuerydslExecutor.java
katharsis-jpa/src/main/java/io/katharsis/jpa/query/querydsl/QuerydslQueryFactory.java
katharsis-jpa/src/main/java/io/katharsis/jpa/query/querydsl/QuerydslRepositoryFilter.java
katharsis-jpa/src/main/java/io/katharsis/jpa/query/querydsl/QuerydslRepositoryFilterBase.java
katharsis-jpa/src/main/java/io/katharsis/jpa/query/querydsl/QuerydslTranslationContext.java
katharsis-jpa/src/main/java/io/katharsis/jpa/query/querydsl/QuerydslTranslationInterceptor.java
katharsis-jpa/src/test/java/io/katharsis/jpa/repository/JpaEntityRepositoryTestBase.java
katharsis-jpa/src/test/java/io/katharsis/jpa/repository/querydsl/JpaEntityRepositoryQuerydslTest.java
katharsis-jpa/src/test/java/io/katharsis/jpa/repository/querydsl/QuerydslRepositoryFilterTest.java
katharsis-jpa/src/test/resources/META-INF/beans.xml

new QuerydslRepositoryFilter will introduced that allows with filterQueryTranslation to intercept and modify the generated QueryDSL queries.

#204 Support to intercept and augment QueryDSL generation in jpa module

---

katharsis-client/src/main/java/io/katharsis/client/module/ClientModule.java
katharsis-core/src/main/java/io/katharsis/internal/boot/KatharsisBoot.java
katharsis-core/src/main/java/io/katharsis/module/CoreModule.java
katharsis-core/src/main/java/io/katharsis/module/Module.java
katharsis-core/src/main/java/io/katharsis/module/ModuleRegistry.java
katharsis-core/src/main/java/io/katharsis/module/SimpleModule.java
katharsis-core/src/main/java/io/katharsis/repository/information/RelationshipRepositoryInformation.java
katharsis-core/src/main/java/io/katharsis/repository/information/RepositoryInformation.java
katharsis-core/src/main/java/io/katharsis/repository/information/RepositoryInformationBuilder.java
katharsis-core/src/main/java/io/katharsis/repository/information/RepositoryInformationBuilderContext.java
katharsis-core/src/main/java/io/katharsis/repository/information/ResourceRepositoryInformation.java
katharsis-core/src/main/java/io/katharsis/repository/information/internal/DefaultRelationshipRepositoryInformationBuilder.java
katharsis-core/src/main/java/io/katharsis/repository/information/internal/DefaultResourceRepositoryInformationBuilder.java
katharsis-core/src/main/java/io/katharsis/repository/information/internal/RelationshipRepositoryInformationImpl.java
katharsis-core/src/main/java/io/katharsis/repository/information/internal/RepositoryInformationImpl.java
katharsis-core/src/main/java/io/katharsis/repository/information/internal/ResourceRepositoryInformationImpl.java
katharsis-core/src/test/java/io/katharsis/internal/boot/KatharsisBootTest.java
katharsis-core/src/test/java/io/katharsis/module/ModuleTest.java
katharsis-core/src/test/java/io/katharsis/module/SimpleModuleTest.java
katharsis-core/src/test/java/io/katharsis/module/TestRepository.java
katharsis-core/src/test/java/io/katharsis/module/TestResource.java
katharsis-jpa/src/test/java/io/katharsis/jpa/query/AbstractJpaTest.java

information extraction from a repository implemented the same way as done for resources (ResourceInfromationBuilder). In the context of #24 where actions need to be implemented this approach allows more flexibility like the jaxrs integration extending the repository information based on the JAXRS annotations (i.e. introduction of actions and configuration of repository url path).

#208 ReposistoryInformationBuilder support

---

katharsis-brave/pom.xml
katharsis-brave/src/main/java/io/katharsis/brave/BraveModule.java
katharsis-brave/src/main/java/io/katharsis/brave/internal/HttpClientBraveIntegration.java
katharsis-brave/src/main/java/io/katharsis/brave/internal/OkHttpBraveIntegration.java
katharsis-brave/src/test/java/io/katharsis/brave/AbstractBraveModuleTest.java
katharsis-brave/src/test/java/io/katharsis/brave/ApacheHttpBraveModuleTest.java
katharsis-brave/src/test/java/io/katharsis/brave/OkHttpBraveModuleTest.java
katharsis-client/pom.xml
katharsis-client/src/main/java/io/katharsis/client/KatharsisClient.java
katharsis-client/src/main/java/io/katharsis/client/http/HttpAdapter.java
katharsis-client/src/main/java/io/katharsis/client/http/HttpAdapterRequest.java
katharsis-client/src/main/java/io/katharsis/client/http/HttpAdapterResponse.java
katharsis-client/src/main/java/io/katharsis/client/http/apache/HttpClientAdapter.java
katharsis-client/src/main/java/io/katharsis/client/http/apache/HttpClientAdapterListener.java
katharsis-client/src/main/java/io/katharsis/client/http/apache/HttpClientAdapterListenerBase.java
katharsis-client/src/main/java/io/katharsis/client/http/apache/HttpClientRequest.java
katharsis-client/src/main/java/io/katharsis/client/http/apache/HttpClientResponse.java
katharsis-client/src/main/java/io/katharsis/client/http/okhttp/OkHttpAdapter.java
katharsis-client/src/main/java/io/katharsis/client/http/okhttp/OkHttpRequest.java
katharsis-client/src/main/java/io/katharsis/client/http/okhttp/OkHttpResponse.java
katharsis-client/src/main/java/io/katharsis/client/internal/AbstractStub.java
katharsis-client/src/main/java/io/katharsis/client/internal/RelationshipRepositoryStubImpl.java
katharsis-client/src/main/java/io/katharsis/client/internal/ResourceRepositoryStubImpl.java
katharsis-client/src/test/java/io/katharsis/client/AbstractClientTest.java
katharsis-client/src/test/java/io/katharsis/client/ApacheHttpClientTest.java
katharsis-client/src/test/java/io/katharsis/client/OkHttpClientTest.java
katharsis-client/src/test/java/io/katharsis/client/QuerySpecClientTest.java
katharsis-jpa/pom.xml
katharsis-parent/pom.xml
katharsis-validation/pom.xml

- make okhttp dependency optional
- let consumer choose implementation
- let KatharsisClient auto-detect implementation
- support tracing for both clients
- OkHttpAdapter implementation
- HttpClientAdapter implementation
- adapter can also be set manually on KatharsisClient

#216 Support apache commons http client in katharsis client

---

katharsis-client/src/test/java/io/katharsis/client/QuerySpecUnknownAttributeClientTest.java
katharsis-core/src/main/java/io/katharsis/queryspec/DefaultQuerySpecDeserializer.java
katharsis-rs/src/main/java/io/katharsis/rs/KatharsisFeature.java

introduced flag with setAllowUnknownAttributes to DefaultQuerySpecDeserializer to ignore unknown attributes. 
e.g. 
deserializer = (DefaultQuerySpecDeserializer) katharsisFeature.getQuerySpecDeserializer();
deserializer.setAllowUnknownAttributes(true);

#193 QuerySpec custom fields in filter

---

katharsis-client/src/main/java/io/katharsis/client/internal/ClientStubInvocationHandler.java
katharsis-client/src/main/java/io/katharsis/client/internal/proxy/CollectionInvocationHandler.java
katharsis-client/src/test/java/io/katharsis/client/ExceptionTest.java
katharsis-client/src/test/java/io/katharsis/client/mock/repository/ScheduleRepositoryImpl.java
katharsis-core/src/test/java/io/katharsis/resource/mock/repository/ScheduleRepository.java

fixed invocationTargetException vs. application specific exception when going trough a proxy. Consumer no longer receives a invocationTargetException. Instead he gets the proper application exception.

#221 Support lazy proxies for katharsis-client

---

katharsis-core/src/main/java/io/katharsis/jackson/serializer/include/IncludedRelationshipExtractor.java
katharsis-core/src/test/java/io/katharsis/jackson/RelationshipContainerSerializerTest.java

Fixes a bug where includes for a relationship field call where not getting serialized in the include block. 
Ex. /project/1/task?include=project now has task project being serialized

#214 Add support for N level inclusions for relationship look up call

---

katharsis-examples/spring-boot-simple-example/src/main/resources/application.properties
katharsis-jpa/src/main/java/io/katharsis/jpa/JpaModule.java
katharsis-spring/pom.xml
katharsis-spring/src/main/java/io/katharsis/spring/boot/KatharsisJpaProperties.java
katharsis-spring/src/main/java/io/katharsis/spring/boot/autoconfigure/KatharsisJpaAutoConfiguration.java
katharsis-spring/src/main/resources/META-INF/spring.factories
katharsis-spring/src/test/java/io/katharsis/spring/boot/SpringBootSimpleExampleApplicationTests.java

This adds auto config for katharsis-jpa in a spring boot application. No java configuration is required in order to standup a basic katharsis api backed by JPA.
Includes several katharsis.jpa properties for more configuration.
The auto configuration is triggered when:
* the beans `EntityManager` and `EntityManagerFactory` exist
* property `katharsis.jpa.enabled=null/true` 
* and only if no other `JpaModule` bean has been created.

Spring boot auto configuration for katharsis-jpa

---

katharsis-cdi/src/main/java/io/katharsis/cdi/internal/CdiTransactionRunner.java

Add a noargs constructor to CdiTransactionRunner in order to fix a deployment issue that occurred at least on TomEE 7.0.2

#280 Fix katharsis-cdi deployment issue

---

katharsis-client/src/test/java/io/katharsis/client/AbstractClientTest.java
katharsis-client/src/test/java/io/katharsis/client/InheritanceClientTest.java
katharsis-client/src/test/java/io/katharsis/client/mock/models/TaskSubType.java
katharsis-client/src/test/java/io/katharsis/client/mock/repository/ProjectToTaskRepository.java
katharsis-client/src/test/java/io/katharsis/client/mock/repository/TaskSubtypeRepository.java
katharsis-core/src/main/java/io/katharsis/core/internal/dispatcher/controller/ResourceUpsert.java
katharsis-core/src/main/java/io/katharsis/core/internal/registry/ResourceRegistryImpl.java
katharsis-core/src/main/java/io/katharsis/core/internal/resource/AnnotationResourceInformationBuilder.java
katharsis-core/src/main/java/io/katharsis/module/ModuleRegistry.java
katharsis-core/src/main/java/io/katharsis/resource/information/ResourceInformation.java
katharsis-core/src/main/java/io/katharsis/resource/registry/RegistryEntry.java
katharsis-core/src/main/java/io/katharsis/resource/registry/ResourceRegistry.java
katharsis-core/src/test/java/io/katharsis/module/TestResourceInformationBuilder.java
katharsis-core/src/test/java/io/katharsis/queryspec/QuerySpecAdapterTest.java
katharsis-core/src/test/java/io/katharsis/resource/ResourceInformationTest.java
katharsis-core/src/test/java/io/katharsis/resource/registry/RegistryEntryTest.java
katharsis-core/src/test/java/io/katharsis/resource/registry/ResourceRegistryTest.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/JpaResourceInformationBuilder.java

some further improvements towards supporting inheritance:
- ResourceInformation carries a pointer to the superResourceType
- RegistryEntry properly links to the parent entry (the superType entry)
- KatharsisClient properly deals with polymorhic collections (resources included in a response where not properly resolved due to wrong resourceType usage, leading to proxies instead of actual objects)

properly support inheritance #278

---

katharsis-core/src/main/java/io/katharsis/resource/information/ResourceInformationBuilderContext.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/QueryFilterBuilder.java
katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/QuerySortBuilder.java
katharsis-jpa/src/main/java/io/katharsis/jpa/meta/JpaMetaProvider.java
katharsis-jpa/src/main/java/io/katharsis/jpa/meta/MetaJpaDataObject.java
katharsis-jpa/src/main/java/io/katharsis/jpa/meta/internal/AbstractEntityMetaProvider.java
katharsis-jpa/src/main/java/io/katharsis/jpa/meta/internal/EmbeddableMetaProvider.java
katharsis-jpa/src/test/java/io/katharsis/jpa/AbstractJpaJerseyTest.java
katharsis-jpa/src/test/java/io/katharsis/jpa/meta/MetaAttributeImplTest.java
katharsis-jpa/src/test/java/io/katharsis/jpa/meta/MetaEntityTest.java
katharsis-jpa/src/test/java/io/katharsis/jpa/meta/MetaLookupTest.java
katharsis-meta/src/main/java/io/katharsis/meta/MetaLookup.java
katharsis-meta/src/main/java/io/katharsis/meta/MetaModule.java
katharsis-meta/src/main/java/io/katharsis/meta/internal/MetaDataObjectProvider.java
katharsis-meta/src/main/java/io/katharsis/meta/internal/MetaDataObjectProviderBase.java
katharsis-meta/src/main/java/io/katharsis/meta/internal/ResourceMetaProviderImpl.java
katharsis-meta/src/main/java/io/katharsis/meta/model/MetaArrayType.java
katharsis-meta/src/main/java/io/katharsis/meta/model/MetaAttribute.java
katharsis-meta/src/main/java/io/katharsis/meta/model/MetaCollectionType.java
katharsis-meta/src/main/java/io/katharsis/meta/model/MetaDataObject.java
katharsis-meta/src/main/java/io/katharsis/meta/model/MetaElement.java
katharsis-meta/src/main/java/io/katharsis/meta/model/MetaMapType.java
katharsis-meta/src/main/java/io/katharsis/meta/model/MetaPrimaryKey.java
katharsis-meta/src/main/java/io/katharsis/meta/model/MetaType.java
katharsis-meta/src/main/java/io/katharsis/meta/provider/MetaProviderContext.java
katharsis-meta/src/test/java/io/katharsis/meta/AbstractMetaJerseyTest.java
katharsis-meta/src/test/java/io/katharsis/meta/MetaModuleTest.java
katharsis-meta/src/test/java/io/katharsis/meta/TestMultipleMetaForSameType.java

- new MetaPrimaryKey extends MetaKey
- MetaPrimaryKey holds whether key is generated or not
- removed some redundant elementType attributes from various types
- started simplifying meta classes by moving further logic out (like elementType computation)
- more testing (which double checks general inheritance support as well)
- replaced deprecated annotations by JsonApiRelation
- sortable/filterable attribute for MetaAttribute in meta model

#289: MetaModule minor improvements

---

katharsis-core/src/main/java/io/katharsis/core/internal/boot/KatharsisBoot.java
katharsis-core/src/test/java/io/katharsis/core/internal/boot/KatharsisBootTest.java

Show friendly error and prevent NPE when setting invalid QuerySpec options in katharsis boot

---

katharsis-jpa/src/main/java/io/katharsis/jpa/JpaEntityRepository.java

When using katharsis-jpa with mapped entity dto,  the resource dto's primary key field is never set when  id is auto generated value, which leads to error.

Fix bug when using jpa entity with mapped dto
