katharsis-core/pom.xml, katharsis-core/src/main/java/io/katharsis/dispatcher/RequestDispatcher.java, katharsis-core/src/main/java/io/katharsis/errorhandling/ErrorResponse.java, katharsis-core/src/main/java/io/katharsis/errorhandling/mapper/ExceptionMapper.java, katharsis-core/src/main/java/io/katharsis/errorhandling/mapper/ExceptionMapperRegistry.java, katharsis-core/src/main/java/io/katharsis/errorhandling/mapper/ExceptionMapperRegistryBuilder.java, katharsis-core/src/main/java/io/katharsis/errorhandling/mapper/JsonApiExceptionMapper.java, katharsis-core/src/main/java/io/katharsis/module/CoreModule.java, katharsis-core/src/main/java/io/katharsis/module/Module.java, katharsis-core/src/main/java/io/katharsis/module/ModuleRegistry.java, katharsis-core/src/main/java/io/katharsis/module/SimpleModule.java, katharsis-core/src/main/java/io/katharsis/resource/information/AnnotationResourceInformationBuilder.java, katharsis-core/src/main/java/io/katharsis/resource/information/ResourceInformationBuilder.java, katharsis-core/src/test/java/io/katharsis/dispatcher/RequestDispatcherTest.java, katharsis-core/src/test/java/io/katharsis/dispatcher/filter/FilterTest.java, katharsis-core/src/test/java/io/katharsis/errorhandling/mapper/ExceptionMapperRegistryTest.java, katharsis-core/src/test/java/io/katharsis/module/ModuleTest.java, katharsis-core/src/test/java/io/katharsis/module/SimpleModuleTest.java, katharsis-core/src/test/java/io/katharsis/module/TestRelationshipRepository.java, katharsis-core/src/test/java/io/katharsis/module/TestRepository.java, katharsis-core/src/test/java/io/katharsis/module/TestResource.java, katharsis-core/src/test/java/io/katharsis/module/TestResourceInformationBuilder.java, katharsis-core/src/test/java/io/katharsis/module/TestResourceLookup.java, katharsis-rs/src/main/java/io/katharsis/rs/KatharsisFeature.java, katharsis-servlet/src/main/java/io/katharsis/invoker/KatharsisInvokerBuilder.java, katharsis-spring/src/main/java/io/katharsis/spring/boot/KatharsisConfigV2.java, katharsis-spring/src/main/java/io/katharsis/spring/boot/KatharsisRegistryConfiguration.java, katharsis-spring/src/main/java/io/katharsis/spring/boot/ModuleConfiguration.java, katharsis-spring/src/main/java/io/katharsis/spring/boot/RequestDispatcherConfiguration.java
=> Module API to allow to extend core katharsis functionality #45 

katharsis-core/src/main/java/io/katharsis/response/JsonApiResponse.java
I think the parameter passed in `JsonApiResponse` are wrong assigned.
=> Assign to corresponding variables

katharsis-core/src/main/java/io/katharsis/repository/RelationshipRepository.java
I think it should be to-many :smile:
=> improve documentation

katharsis-core/src/main/java/io/katharsis/jackson/serializer/include/IncludedRelationshipExtractor.java, katharsis-core/src/test/java/io/katharsis/jackson/RelationshipContainerSerializerTest.java, katharsis-core/src/test/java/io/katharsis/resource/ResourceInformationBuilderTest.java, katharsis-core/src/test/java/io/katharsis/resource/mock/models/Task.java
Fix nested inclusion call where an empty array list that points to another empty array
=> #93 Fix nested inclusion serializer

katharsis-core/src/main/java/io/katharsis/utils/ClassUtils.java, katharsis-core/src/test/java/io/katharsis/utils/ClassUtilsTest.java
When running Katharsis that has AbstractResource class there are bridged methods that clash with actual implementation.
=> #97 Check that a method is not bridged to prevent instance clash

katharsis-client/src/main/java/io/katharsis/client/KatharsisClient.java, katharsis-client/src/main/java/io/katharsis/client/internal/AbstractStub.java, katharsis-client/src/test/java/io/katharsis/client/RequestUrlBuilderTest.java, katharsis-core/src/main/java/io/katharsis/resource/registry/ConstantServiceUrlProvider.java, katharsis-core/src/main/java/io/katharsis/resource/registry/ResourceRegistry.java, katharsis-core/src/main/java/io/katharsis/resource/registry/ResourceRegistryBuilder.java, katharsis-core/src/main/java/io/katharsis/resource/registry/ServiceUrlProvider.java, katharsis-core/src/test/java/io/katharsis/dispatcher/RequestDispatcherTest.java, katharsis-core/src/test/java/io/katharsis/dispatcher/controller/BaseControllerTest.java, katharsis-core/src/test/java/io/katharsis/dispatcher/filter/FilterTest.java, katharsis-core/src/test/java/io/katharsis/dispatcher/registry/ControllerRegistryTest.java, katharsis-core/src/test/java/io/katharsis/jackson/BaseSerializerTest.java, katharsis-core/src/test/java/io/katharsis/jackson/IncludedRelationshipExtractorTest.java, katharsis-core/src/test/java/io/katharsis/module/ModuleTest.java, katharsis-core/src/test/java/io/katharsis/request/path/PathBuilderTest.java, katharsis-core/src/test/java/io/katharsis/resource/registry/ResourceRegistryBuilderTest.java, katharsis-core/src/test/java/io/katharsis/resource/registry/ResourceRegistryTest.java, katharsis-examples/dropwizard-simple-example/configuration.yml, katharsis-examples/dropwizard-simple-example/src/main/java/io/katharsis/example/dropwizardSimple/DropwizardConfiguration.java, katharsis-examples/dropwizard-simple-example/src/main/java/io/katharsis/example/dropwizardSimple/DropwizardService.java, katharsis-examples/jersey-example/src/main/java/io/katharsis/example/jersey/JerseyApplication.java, katharsis-rs/src/main/java/io/katharsis/resource/registry/UriInfoServiceUrlProvider.java, katharsis-rs/src/main/java/io/katharsis/rs/KatharsisFeature.java, katharsis-rs/src/main/java/io/katharsis/rs/KatharsisFilter.java, katharsis-servlet/src/main/java/io/katharsis/invoker/KatharsisInvokerBuilder.java, katharsis-spring/pom.xml, katharsis-spring/src/main/java/io/katharsis/spring/boot/KatharsisRegistryConfiguration.java
Waiting to hear from others. What resource does the drop-wizard example respond on? 
This appears to cover all cases but I need to be sure. Solving #42
=> Issue #42 Addressed

katharsis-examples/pom.xml, katharsis-examples/vertx-simple/pom.xml, katharsis-examples/vertx-simple/src/main/java/io/katharsis/vertx/examples/KatharsisVerticle.java, katharsis-examples/vertx-simple/src/main/java/io/katharsis/vertx/examples/Main.java, katharsis-examples/vertx-simple/src/main/java/io/katharsis/vertx/examples/domain/Project.java, katharsis-examples/vertx-simple/src/main/java/io/katharsis/vertx/examples/domain/Task.java, katharsis-examples/vertx-simple/src/main/java/io/katharsis/vertx/examples/repository/ProjectRepository.java, katharsis-examples/vertx-simple/src/main/java/io/katharsis/vertx/examples/repository/TaskRepository.java, katharsis-examples/vertx-simple/src/main/java/io/katharsis/vertx/examples/repository/TaskToProjectRepository.java, katharsis-vertx/pom.xml, katharsis-vertx/src/main/java/io/katharsis/vertx/DefaultParameterProvider.java, katharsis-vertx/src/main/java/io/katharsis/vertx/DefaultParameterProviderFactory.java, katharsis-vertx/src/main/java/io/katharsis/vertx/JsonApiMediaTypeHandler.java, katharsis-vertx/src/main/java/io/katharsis/vertx/KatharsisHandler.java, katharsis-vertx/src/main/java/io/katharsis/vertx/KatharsisHandlerFactory.java, katharsis-vertx/src/main/java/io/katharsis/vertx/KatharsisVertxException.java, katharsis-vertx/src/main/java/io/katharsis/vertx/ParameterProviderFactory.java, katharsis-vertx/src/main/java/io/katharsis/vertx/QueryParamsUtils.java, pom.xml
* adds Vertx integration module
* adds vertx example
=> Added katharsis vertx and katharsis vertx example

katharsis-rs/pom.xml, katharsis-rs/src/main/java/io/katharsis/rs/KatharsisFilter.java
Ensure KatharsisFilter is applied last since it prevents the rest of the filters from running.
Addresses #123
=> Ensure KatharsisFilter is applied last

katharsis-jpa/src/main/java/io/katharsis/jpa/internal/meta/MetaAttribute.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/meta/impl/AbstractMetaEntityAttributeImpl.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/meta/impl/AbstractMetaEntityImpl.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/meta/impl/MetaAttributeImpl.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/meta/impl/MetaEntityAttributeImpl.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/meta/impl/MetaMapAttributeImpl.java, katharsis-jpa/src/test/java/io/katharsis/jpa/meta/MetaEntityTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/model/TestMappedSuperclassWithPk.java, katharsis-jpa/src/test/java/io/katharsis/jpa/model/TestSubclassWithSuperclassPk.java
added support for primary keys on mapped superclasses.
=> #15 jpa module

katharsis-jpa/src/main/java/io/katharsis/jpa/JpaEntityRepository.java, katharsis-jpa/src/main/java/io/katharsis/jpa/JpaModule.java, katharsis-jpa/src/main/java/io/katharsis/jpa/JpaRelationshipRepository.java, katharsis-jpa/src/main/java/io/katharsis/jpa/JpaRepositoryFilter.java, katharsis-jpa/src/main/java/io/katharsis/jpa/JpaRepositoryFilterBase.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/JpaRepositoryBase.java, katharsis-jpa/src/test/java/io/katharsis/jpa/repository/JpaEntityRepositoryTestBase.java, katharsis-jpa/src/test/java/io/katharsis/jpa/repository/JpaListenerTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/repository/JpaRelationshipRepositoryTestBase.java
allow to change readablity, updateablity, deleteablity and insertablity with boolean flags.
Updated JpaRepositoryFilter api to allow such customizations upon creation.
=> #15 JPA adapter

katharsis-jpa/src/main/java/io/katharsis/jpa/JpaModule.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/JpaQueryFactoryBase.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/ComputedAttributeRegistryImpl.java, katharsis-jpa/src/main/java/io/katharsis/jpa/query/JpaQueryFactory.java, katharsis-jpa/src/main/java/io/katharsis/jpa/query/JpaQueryFactoryContext.java, katharsis-jpa/src/main/java/io/katharsis/jpa/query/criteria/JpaCriteriaQueryFactory.java, katharsis-jpa/src/main/java/io/katharsis/jpa/query/querydsl/QuerydslQueryFactory.java, katharsis-jpa/src/test/java/io/katharsis/jpa/AbstractJpaJerseyTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/AbstractJpaTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/criteria/BasicCriteriaTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/criteria/ComputedAttributeCriteriaTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/criteria/EmbeddableIdCriteriaTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/criteria/JoinedTableInheritanceCriteriaTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/criteria/SingleTableInheritanceCriteriaTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/criteria/TablePerClassInheritanceCriteriaTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/querydsl/BasicQuerydslTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/querydsl/ComputedAttributeQuerydslTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/querydsl/EmbeddableIdQuerydslTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/querydsl/JoinedTableInheritanceQuerydslTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/querydsl/SingleTableInheritanceQuerydslTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/query/querydsl/TablePerClassInheritanceQuerydslTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/repository/JpaListenerTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/repository/criteria/JpaEntityRepositoryCriteriaTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/repository/criteria/JpaRelationshipRepositoryCriteriaTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/repository/querydsl/JpaEntityRepositoryQuerydslTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/repository/querydsl/JpaRelationshipRepositoryQuerydslTest.java
simplified API to switch between criteria and querydsl api.
=> #15 JPA adapter cleanup

katharsis-core/src/main/java/io/katharsis/errorhandling/exception/KatharsisMappableException.java, katharsis-core/src/main/java/io/katharsis/jackson/exception/ParametersDeserializationException.java, katharsis-core/src/main/java/io/katharsis/queryParams/DefaultQueryParamsParser.java, katharsis-core/src/main/java/io/katharsis/queryParams/JsonApiQueryParamsParser.java, katharsis-core/src/main/java/io/katharsis/queryParams/QueryParams.java, katharsis-core/src/main/java/io/katharsis/queryParams/QueryParamsBuilder.java, katharsis-core/src/main/java/io/katharsis/queryParams/QueryParamsParser.java, katharsis-core/src/main/java/io/katharsis/queryParams/context/AbstractQueryParamsParserContext.java, katharsis-core/src/main/java/io/katharsis/queryParams/context/QueryParamsParserContext.java, katharsis-core/src/main/java/io/katharsis/queryParams/context/SimpleQueryParamsParserContext.java, katharsis-core/src/main/java/io/katharsis/queryspec/internal/QueryParamsAdapterBuilder.java, katharsis-core/src/test/java/io/katharsis/module/TestResource.java, katharsis-core/src/test/java/io/katharsis/module/TestResourceInformationBuilder.java, katharsis-core/src/test/java/io/katharsis/queryParams/DefaultQueryParamsParserTest.java, katharsis-core/src/test/java/io/katharsis/queryParams/JsonApiQueryParamsParserTest.java, katharsis-core/src/test/java/io/katharsis/queryParams/QueryParamsBuilderTest.java, katharsis-rs/src/main/java/io/katharsis/rs/JaxRsQueryParamsParserContext.java, katharsis-rs/src/main/java/io/katharsis/rs/KatharsisFilter.java, katharsis-servlet/src/main/java/io/katharsis/invoker/KatharsisInvoker.java, katharsis-servlet/src/main/java/io/katharsis/servlet/ServletQueryParamsParserContext.java, katharsis-spring/src/main/java/io/katharsis/spring/KatharsisFilterV2.java, katharsis-spring/src/main/java/io/katharsis/spring/SpringQueryParamsParserContext.java
This is to fix the merge conflicts of #115 so that @chb0github can merge it.
=> Adhere to JSON API spec

katharsis-client/src/main/java/io/katharsis/client/internal/AbstractStub.java, katharsis-client/src/test/java/io/katharsis/client/AbstractClientTest.java, katharsis-client/src/test/java/io/katharsis/client/HeadersTest.java, katharsis-client/src/test/java/io/katharsis/client/KatharsisTestFeature.java, katharsis-client/src/test/java/io/katharsis/client/TestRequestFilter.java
As discussed in https://github.com/katharsis-project/katharsis-framework/issues/117#issuecomment-246190999
=> Send Accept header on client API calls

katharsis-core/src/main/java/io/katharsis/queryspec/DefaultQuerySpecDeserializer.java, katharsis-core/src/test/java/io/katharsis/queryspec/repository/DefaultQuerySpecDeserializerTest.java
added support to sort by multiple attributes separated by comma.
=> #113: json api compliant parameter handling

katharsis-client/src/main/java/io/katharsis/client/KatharsisClient.java, katharsis-client/src/main/java/io/katharsis/client/module/ClientModule.java, katharsis-client/src/test/java/io/katharsis/client/AbstractClientTest.java, katharsis-core/src/main/java/io/katharsis/resource/registry/ResourceRegistry.java
removed use of reflections from katharsis-client. Resources are now automatically discovered once a given stub is requested. No need to specify resource search package. As a result, startup performance is much improved as well.
=> #184 Simplify setup of Katharsis

katharsis-brave/src/main/java/io/katharsis/brave/BraveModule.java, katharsis-brave/src/main/java/io/katharsis/brave/internal/BraveRepositoryFilter.java, katharsis-brave/src/test/java/io/katharsis/brave/BraveModuleTest.java, katharsis-brave/src/test/java/io/katharsis/brave/mock/models/Task.java, katharsis-brave/src/test/java/io/katharsis/brave/mock/repository/TaskRepository.java, katharsis-core/src/main/java/io/katharsis/internal/boot/KatharsisBoot.java
added integration into zipkin/brave with a new "BraveModule" hosted in katharsis-brave. The module can simply be added to KatharsisClient and will integrate Zipkin/Brave accordingly.
=> #179 Support tracing in katharsis

katharsis-client/src/main/java/io/katharsis/client/internal/BaseResponseDeserializer.java, katharsis-client/src/main/java/io/katharsis/client/response/JsonLinksInformation.java, katharsis-client/src/main/java/io/katharsis/client/response/JsonMetaInformation.java, katharsis-client/src/main/java/io/katharsis/client/response/ResourceList.java, katharsis-client/src/test/java/io/katharsis/client/InformationClientTest.java, katharsis-client/src/test/java/io/katharsis/client/QuerySpecClientTest.java, katharsis-client/src/test/java/io/katharsis/client/mock/repository/ProjectRepository.java
ResourceList.getMetaInformation(Class) and ResourceList.getLinksInformation(Class) introduced to get type-safe access to meta and links information.
repository interfaces should be introduced in a second step.
=> #203 Support links/meta deserialization in katharsis-client

katharsis-client/src/main/java/io/katharsis/client/KatharsisClient.java, katharsis-core/src/main/java/io/katharsis/resource/information/ResourceInformation.java, katharsis-jpa/src/main/java/io/katharsis/jpa/JpaModule.java, katharsis-jpa/src/main/java/io/katharsis/jpa/JpaRepositoryConfig.java, katharsis-jpa/src/main/java/io/katharsis/jpa/annotations/JpaMergeRelations.java, katharsis-jpa/src/main/java/io/katharsis/jpa/annotations/JpaResource.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/JpaRepositoryUtils.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/JpaResourceInformationBuilder.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/meta/MetaElement.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/meta/impl/MetaDataObjectImpl.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/meta/impl/MetaElementImpl.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/query/AbstractQueryExecutorImpl.java, katharsis-jpa/src/test/java/io/katharsis/jpa/AbstractJpaJerseyTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/JpaPartialEntityExposureTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/JpaResourceInformationBuilderTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/merge/MergeTest.java, katharsis-jpa/src/test/java/io/katharsis/jpa/merge/MergedResource.java, katharsis-jpa/src/test/java/io/katharsis/jpa/merge/MergedResourceMapper.java, katharsis-jpa/src/test/java/io/katharsis/jpa/model/TestEntity.java, katharsis-jpa/src/test/java/io/katharsis/jpa/repository/JpaRepositoryConfigTest.java, katharsis-validation/src/test/java/io/katharsis/validation/AbstractValidationTest.java
- @JpaResource annotation
- @JpaMergeRelations annotation
to allow to map to dtos subclassing entities and pulling in relations.
=> #15 JPA adapter improvements

katharsis-client/src/main/java/io/katharsis/client/KatharsisClient.java, katharsis-core/src/main/java/io/katharsis/jackson/serializer/include/IncludedRelationshipExtractor.java, katharsis-core/src/main/java/io/katharsis/repository/information/internal/DefaultRelationshipRepositoryInformationBuilder.java, katharsis-core/src/main/java/io/katharsis/request/path/PathBuilder.java, katharsis-core/src/main/java/io/katharsis/resource/field/ResourceAttributesBridge.java, katharsis-core/src/main/java/io/katharsis/resource/field/ResourceField.java, katharsis-core/src/main/java/io/katharsis/resource/information/AnnotationResourceInformationBuilder.java, katharsis-core/src/main/java/io/katharsis/resource/information/ResourceInformation.java, katharsis-core/src/test/java/io/katharsis/module/TestResourceInformationBuilder.java, katharsis-core/src/test/java/io/katharsis/queryspec/QuerySpecAdapterTest.java, katharsis-core/src/test/java/io/katharsis/resource/ResourceInformationTest.java, katharsis-core/src/test/java/io/katharsis/resource/field/ResourceAttributesBridgeTest.java, katharsis-core/src/test/java/io/katharsis/resource/field/ResourceFieldTest.java, katharsis-core/src/test/java/io/katharsis/resource/registry/RegistryEntryTest.java, katharsis-core/src/test/java/io/katharsis/resource/registry/ResourceRegistryTest.java, katharsis-core/src/test/java/io/katharsis/response/ResponseContractTest.java, katharsis-core/src/test/java/io/katharsis/response/field/FieldOrderedComparatorTest.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/JpaResourceInformationBuilder.java, katharsis-jpa/src/main/java/io/katharsis/jpa/internal/meta/impl/MetaResourceImpl.java, katharsis-jpa/src/test/java/io/katharsis/jpa/JpaPartialEntityExposureTest.java
cleanup of information builders:
- order contract of fields ensured with lists
- moved logic of relation/id/meta/... into field
- simplified constructors
- fixed jpa issues
=> #223 ResourceInformationBuilder broken

katharsis-core/src/main/java/io/katharsis/resource/registry/DefaultResourceLookup.java, katharsis-core/src/main/java/io/katharsis/resource/registry/repository/adapter/ResponseRepositoryAdapter.java, katharsis-core/src/test/java/io/katharsis/repository/filter/RepositoryFilterTest.java, katharsis-core/src/test/java/io/katharsis/resource/mock/repository/ScheduleRepository.java, katharsis-core/src/test/java/io/katharsis/resource/mock/repository/ScheduleRepositoryImpl.java
added support to filter meta and links information obtained from a ResourceList
=> #218 RepositoryFliter support for ResourceList

katharsis-core/src/main/java/io/katharsis/dispatcher/controller/resource/FieldResourceGet.java, katharsis-jpa/src/test/java/io/katharsis/jpa/JpaQuerySpecEndToEndTest.java
updated implementation to get resource type from resource registry and added a test case.
=> #255 FieldResourceGet makes us of annotations instead of ResourceInformation 

katharsis-core/src/main/java/io/katharsis/internal/boot/KatharsisBoot.java, katharsis-core/src/main/java/io/katharsis/queryspec/DefaultQuerySpecDeserializer.java, katharsis-core/src/test/java/io/katharsis/internal/boot/KatharsisBootTest.java, katharsis-core/src/test/java/io/katharsis/queryspec/repository/DefaultQuerySpecDeserializerTest.java, katharsis-spring/src/main/java/io/katharsis/spring/boot/KatharsisSpringBootProperties.java, katharsis-spring/src/main/java/io/katharsis/spring/boot/v3/KatharsisConfigV3.java
* adds max-page-limit property
* cleans up documentation for spring boot properties configuration
=> #264 Properties to configure default katharsis paging behavior

katharsis-core/src/main/java/io/katharsis/dispatcher/controller/resource/ResourceGet.java, katharsis-core/src/test/java/io/katharsis/dispatcher/controller/resource/ResourceGetTest.java
Now throwing `ResourceNotFoundException` in `findOne` method should result in building proper server response.
=> Respond with 404 status for single resources that do not exist - #272

katharsis-core/src/main/java/io/katharsis/core/internal/dispatcher/controller/ResourcePatch.java, katharsis-core/src/test/java/io/katharsis/core/internal/dispatcher/controller/resource/ResourcePatchTest.java
fixed by checking for null instead of contains.
=> NPE in ResourcePatch.updateValues #351

katharsis-jpa/src/main/java/io/katharsis/jpa/JpaEntityRepository.java, katharsis-jpa/src/test/java/io/katharsis/jpa/model/SequenceEntity.java, katharsis-jpa/src/test/java/io/katharsis/jpa/repository/JpaEntityRepositoryTestBase.java
added support/testing for generated primary keys
=> JpaEntityRepository cannot create resource #362

katharsis-core/src/main/java/io/katharsis/core/internal/boot/KatharsisBoot.java, katharsis-core/src/main/java/io/katharsis/core/internal/query/QuerySpecAdapter.java, katharsis-core/src/main/java/io/katharsis/legacy/internal/ParametersFactory.java, katharsis-core/src/main/java/io/katharsis/legacy/internal/QueryParamsAdapter.java, katharsis-core/src/main/java/io/katharsis/legacy/internal/QueryParamsAdapterBuilder.java, katharsis-core/src/main/java/io/katharsis/legacy/queryParams/DefaultQueryParamsConverter.java, katharsis-core/src/main/java/io/katharsis/legacy/queryParams/QueryParams.java, katharsis-core/src/main/java/io/katharsis/legacy/queryParams/QueryParamsConverter.java, katharsis-core/src/main/java/io/katharsis/legacy/queryParams/params/FilterParams.java, katharsis-core/src/main/java/io/katharsis/legacy/queryParams/params/GroupingParams.java, katharsis-core/src/main/java/io/katharsis/legacy/queryParams/params/IncludedFieldsParams.java, katharsis-core/src/main/java/io/katharsis/legacy/queryParams/params/IncludedRelationsParams.java, katharsis-core/src/main/java/io/katharsis/legacy/queryParams/params/SortingParams.java, katharsis-core/src/main/java/io/katharsis/legacy/queryParams/params/TypedParams.java, katharsis-core/src/main/java/io/katharsis/queryspec/QuerySpec.java, katharsis-core/src/main/java/io/katharsis/repository/request/QueryAdapter.java, katharsis-core/src/test/java/io/katharsis/core/internal/dispatcher/controller/BaseControllerTest.java, katharsis-core/src/test/java/io/katharsis/core/internal/dispatcher/controller/resource/FieldResourceGetTest.java, katharsis-core/src/test/java/io/katharsis/legacy/queryParams/AbstractQueryParamsTest.java, katharsis-core/src/test/java/io/katharsis/legacy/queryParams/DefaultQueryParamsConverterTest.java, katharsis-core/src/test/java/io/katharsis/legacy/queryParams/QueryParamsAdapterTest.java, katharsis-core/src/test/java/io/katharsis/legacy/queryParams/QueryParamsTest.java, katharsis-servlet/src/main/java/io/katharsis/invoker/internal/legacy/KatharsisInvokerBuilder.java, katharsis-spring/src/main/java/io/katharsis/spring/legacy/RequestDispatcherConfiguration.java
=> QuerySpec -> QueryParams converter
